# Generated by Django 4.1.3 on 2023-08-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LisheApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidhaaZetu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=500)),
                ('ProductDescription', models.TextField(blank=True, max_length=1000, null=True)),
                ('ProductImage', models.ImageField(blank=True, null=True, upload_to='media/ElimuYaLisheImages/')),
                ('status', models.CharField(blank=True, default='Bidhaa Zetu', max_length=500, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElimuYaLishe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodCategory', models.CharField(max_length=500)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='media/ElimuYaLisheImages/')),
                ('status', models.CharField(blank=True, default='ELIMU YA LISHE', max_length=500, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lishe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=500)),
                ('ItemDescription', models.TextField(blank=True, max_length=1000, null=True)),
                ('ItemImage', models.ImageField(blank=True, null=True, upload_to='media/LisheImages/')),
                ('status', models.CharField(blank=True, default='LISHE', max_length=500, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
