# Generated by Django 4.1.3 on 2023-08-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LisheApp', '0002_bidhaazetu_elimuyalishe_lishe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidhaazetu',
            options={'verbose_name_plural': 'BidhaaZetu'},
        ),
        migrations.AlterModelOptions(
            name='elimuyalishe',
            options={'verbose_name_plural': 'ElimuYaLishe'},
        ),
        migrations.AlterModelOptions(
            name='lishe',
            options={'verbose_name_plural': 'Lishe'},
        ),
    ]
