# Generated by Django 4.1.3 on 2023-08-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LisheApp', '0003_alter_bidhaazetu_options_alter_elimuyalishe_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DayName', models.CharField(default='Day one', max_length=500)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Watoto',
            },
        ),
        migrations.CreateModel(
            name='WatotoDayFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(blank=True, choices=[('ASUBUHI', 'ASUBUHI'), ('MCHANA', 'MCHANA'), ('JIONI', 'JIONI'), ('USIKU', 'USIKU')], max_length=100, null=True)),
                ('DayName', models.CharField(default='Day five', max_length=500)),
                ('DayDescription', models.TextField(blank=True, max_length=1000, null=True)),
                ('DayImage', models.ImageField(blank=True, null=True, upload_to='media/ElimuYaLisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'WatotoDayFive',
            },
        ),
        migrations.CreateModel(
            name='WatotoDayFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(blank=True, choices=[('ASUBUHI', 'ASUBUHI'), ('MCHANA', 'MCHANA'), ('JIONI', 'JIONI'), ('USIKU', 'USIKU')], max_length=100, null=True)),
                ('DayName', models.CharField(default='Day four', max_length=500)),
                ('DayDescription', models.TextField(blank=True, max_length=1000, null=True)),
                ('DayImage', models.ImageField(blank=True, null=True, upload_to='media/ElimuYaLisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'WatotoDayFour',
            },
        ),
        migrations.CreateModel(
            name='WatotoDayOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(blank=True, choices=[('ASUBUHI', 'ASUBUHI'), ('MCHANA', 'MCHANA'), ('JIONI', 'JIONI'), ('USIKU', 'USIKU')], max_length=100, null=True)),
                ('DayName', models.CharField(default='Day one', max_length=500)),
                ('DayDescription', models.TextField(blank=True, max_length=1000, null=True)),
                ('DayImage', models.ImageField(blank=True, null=True, upload_to='media/ElimuYaLisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'WatotoDayOne',
            },
        ),
        migrations.CreateModel(
            name='WatotoDaySeven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(blank=True, choices=[('ASUBUHI', 'ASUBUHI'), ('MCHANA', 'MCHANA'), ('JIONI', 'JIONI'), ('USIKU', 'USIKU')], max_length=100, null=True)),
                ('DayName', models.CharField(default='Day seven', max_length=500)),
                ('DayDescription', models.TextField(blank=True, max_length=1000, null=True)),
                ('DayImage', models.ImageField(blank=True, null=True, upload_to='media/ElimuYaLisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'WatotoDaySeven',
            },
        ),
        migrations.CreateModel(
            name='WatotoDaySix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(blank=True, choices=[('ASUBUHI', 'ASUBUHI'), ('MCHANA', 'MCHANA'), ('JIONI', 'JIONI'), ('USIKU', 'USIKU')], max_length=100, null=True)),
                ('DayName', models.CharField(default='Day six', max_length=500)),
                ('DayDescription', models.TextField(blank=True, max_length=1000, null=True)),
                ('DayImage', models.ImageField(blank=True, null=True, upload_to='media/ElimuYaLisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'WatotoDaySix',
            },
        ),
        migrations.CreateModel(
            name='WatotoDayThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(blank=True, choices=[('ASUBUHI', 'ASUBUHI'), ('MCHANA', 'MCHANA'), ('JIONI', 'JIONI'), ('USIKU', 'USIKU')], max_length=100, null=True)),
                ('DayName', models.CharField(default='Day three', max_length=500)),
                ('DayDescription', models.TextField(blank=True, max_length=1000, null=True)),
                ('DayImage', models.ImageField(blank=True, null=True, upload_to='media/ElimuYaLisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'WatotoDayThree',
            },
        ),
        migrations.CreateModel(
            name='WatotoDayTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(blank=True, choices=[('ASUBUHI', 'ASUBUHI'), ('MCHANA', 'MCHANA'), ('JIONI', 'JIONI'), ('USIKU', 'USIKU')], max_length=100, null=True)),
                ('DayName', models.CharField(default='Day two', max_length=500)),
                ('DayDescription', models.TextField(blank=True, max_length=1000, null=True)),
                ('DayImage', models.ImageField(blank=True, null=True, upload_to='media/ElimuYaLisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'WatotoDayTwo',
            },
        ),
    ]
