# Generated by Django 4.1.3 on 2023-08-15 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LisheApp', '0004_watoto_watotodayfive_watotodayfour_watotodayone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(blank=True, choices=[('ASUBUHI', 'ASUBUHI'), ('MCHANA', 'MCHANA'), ('JIONI', 'JIONI'), ('USIKU', 'USIKU')], max_length=100, null=True)),
                ('DayName', models.CharField(default='Day five', max_length=500)),
                ('DayDescription', models.TextField(blank=True, max_length=1000, null=True)),
                ('DayImage', models.ImageField(blank=True, null=True, upload_to='media/ElimuYaLisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'DayFive',
            },
        ),
        migrations.CreateModel(
            name='DayFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(blank=True, choices=[('ASUBUHI', 'ASUBUHI'), ('MCHANA', 'MCHANA'), ('JIONI', 'JIONI'), ('USIKU', 'USIKU')], max_length=100, null=True)),
                ('DayName', models.CharField(default='Day four', max_length=500)),
                ('DayDescription', models.TextField(blank=True, max_length=1000, null=True)),
                ('DayImage', models.ImageField(blank=True, null=True, upload_to='media/ElimuYaLisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'DayFour',
            },
        ),
        migrations.CreateModel(
            name='DayOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(blank=True, choices=[('ASUBUHI', 'ASUBUHI'), ('MCHANA', 'MCHANA'), ('JIONI', 'JIONI'), ('USIKU', 'USIKU')], max_length=100, null=True)),
                ('DayName', models.CharField(default='Day one', max_length=500)),
                ('DayDescription', models.TextField(blank=True, max_length=1000, null=True)),
                ('DayImage', models.ImageField(blank=True, null=True, upload_to='media/ElimuYaLisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'DayOne',
            },
        ),
        migrations.CreateModel(
            name='DaySeven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(blank=True, choices=[('ASUBUHI', 'ASUBUHI'), ('MCHANA', 'MCHANA'), ('JIONI', 'JIONI'), ('USIKU', 'USIKU')], max_length=100, null=True)),
                ('DayName', models.CharField(default='Day seven', max_length=500)),
                ('DayDescription', models.TextField(blank=True, max_length=1000, null=True)),
                ('DayImage', models.ImageField(blank=True, null=True, upload_to='media/ElimuYaLisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'DaySeven',
            },
        ),
        migrations.CreateModel(
            name='DaySix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(blank=True, choices=[('ASUBUHI', 'ASUBUHI'), ('MCHANA', 'MCHANA'), ('JIONI', 'JIONI'), ('USIKU', 'USIKU')], max_length=100, null=True)),
                ('DayName', models.CharField(default='Day six', max_length=500)),
                ('DayDescription', models.TextField(blank=True, max_length=1000, null=True)),
                ('DayImage', models.ImageField(blank=True, null=True, upload_to='media/ElimuYaLisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'DaySix',
            },
        ),
        migrations.CreateModel(
            name='DayThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(blank=True, choices=[('ASUBUHI', 'ASUBUHI'), ('MCHANA', 'MCHANA'), ('JIONI', 'JIONI'), ('USIKU', 'USIKU')], max_length=100, null=True)),
                ('DayName', models.CharField(default='Day three', max_length=500)),
                ('DayDescription', models.TextField(blank=True, max_length=1000, null=True)),
                ('DayImage', models.ImageField(blank=True, null=True, upload_to='media/ElimuYaLisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'DayThree',
            },
        ),
        migrations.CreateModel(
            name='DayTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(blank=True, choices=[('ASUBUHI', 'ASUBUHI'), ('MCHANA', 'MCHANA'), ('JIONI', 'JIONI'), ('USIKU', 'USIKU')], max_length=100, null=True)),
                ('DayName', models.CharField(default='Day two', max_length=500)),
                ('DayDescription', models.TextField(blank=True, max_length=1000, null=True)),
                ('DayImage', models.ImageField(blank=True, null=True, upload_to='media/ElimuYaLisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'DayTwo',
            },
        ),
        migrations.CreateModel(
            name='MakundiYaChakula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='media/MakundiYaChakulaImages/')),
                ('status', models.CharField(blank=True, default='ELIMU YA LISHE', max_length=500, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'MakundiYaChakula',
            },
        ),
        migrations.CreateModel(
            name='PosterNaPicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='media/PosterNaPichaImages/')),
                ('status', models.CharField(blank=True, default='ELIMU YA LISHE', max_length=500, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'PosterNaPicha',
            },
        ),
        migrations.CreateModel(
            name='Vyakula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='WANGA', max_length=500)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Vyakula',
            },
        ),
        migrations.RenameModel(
            old_name='Watoto',
            new_name='Days',
        ),
        migrations.DeleteModel(
            name='WatotoDayFive',
        ),
        migrations.DeleteModel(
            name='WatotoDayFour',
        ),
        migrations.DeleteModel(
            name='WatotoDayOne',
        ),
        migrations.DeleteModel(
            name='WatotoDaySeven',
        ),
        migrations.DeleteModel(
            name='WatotoDaySix',
        ),
        migrations.DeleteModel(
            name='WatotoDayThree',
        ),
        migrations.DeleteModel(
            name='WatotoDayTwo',
        ),
        migrations.AlterModelOptions(
            name='days',
            options={'verbose_name_plural': 'Days'},
        ),
        migrations.AddField(
            model_name='makundiyachakula',
            name='FoodCategory',
            field=models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.vyakula'),
        ),
    ]
