# Generated by Django 4.1.3 on 2023-08-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LisheApp', '0005_dayfive_dayfour_dayone_dayseven_daysix_daythree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makundiyachakula',
            name='FoodCategory',
            field=models.CharField(default='WANGA', max_length=500),
        ),
        migrations.DeleteModel(
            name='Vyakula',
        ),
    ]
