# Generated by Django 4.1.3 on 2023-08-15 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LisheApp', '0008_alter_dayseven_dayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayfive',
            name='DayName',
            field=models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.days'),
        ),
        migrations.AlterField(
            model_name='dayfour',
            name='DayName',
            field=models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.days'),
        ),
        migrations.AlterField(
            model_name='dayone',
            name='DayName',
            field=models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.days'),
        ),
        migrations.AlterField(
            model_name='daythree',
            name='DayName',
            field=models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.days'),
        ),
        migrations.AlterField(
            model_name='daytwo',
            name='DayName',
            field=models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.days'),
        ),
    ]
