# Generated by Django 4.1.3 on 2023-08-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LisheApp', '0009_alter_dayfive_dayname_alter_dayfour_dayname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayfive',
            name='DayName',
            field=models.CharField(default='Day five', max_length=500),
        ),
        migrations.AlterField(
            model_name='dayfour',
            name='DayName',
            field=models.CharField(default='Day four', max_length=500),
        ),
        migrations.AlterField(
            model_name='dayone',
            name='DayName',
            field=models.CharField(default='Day one', max_length=500),
        ),
        migrations.AlterField(
            model_name='dayseven',
            name='DayName',
            field=models.CharField(default='Day seven', max_length=500),
        ),
        migrations.AlterField(
            model_name='daysix',
            name='DayName',
            field=models.CharField(default='Day six', max_length=500),
        ),
        migrations.AlterField(
            model_name='daythree',
            name='DayName',
            field=models.CharField(default='Day three', max_length=500),
        ),
        migrations.AlterField(
            model_name='daytwo',
            name='DayName',
            field=models.CharField(default='Day two', max_length=500),
        ),
    ]
