# Generated by Django 4.1.3 on 2023-08-22 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LisheApp', '0011_rename_foodcategory_elimuyalishe_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Week 1', max_length=500)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Weeks',
            },
        ),
        migrations.CreateModel(
            name='Week9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Week 1', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week9',
            },
        ),
        migrations.CreateModel(
            name='Week8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Week 1', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week8',
            },
        ),
        migrations.CreateModel(
            name='Week7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Week 1', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week7',
            },
        ),
        migrations.CreateModel(
            name='Week6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Week 1', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week6',
            },
        ),
        migrations.CreateModel(
            name='Week5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Week 1', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week5',
            },
        ),
        migrations.CreateModel(
            name='Week4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Week 1', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week4',
            },
        ),
        migrations.CreateModel(
            name='Week3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Week 1', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week3',
            },
        ),
        migrations.CreateModel(
            name='Week2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Week 1', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week2',
            },
        ),
        migrations.CreateModel(
            name='Week10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Week 1', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week10',
            },
        ),
        migrations.CreateModel(
            name='Week1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Week 1', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week1',
            },
        ),
        migrations.CreateModel(
            name='TaarifaZaUjauzito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='UJAZO WA MTOTO', max_length=500)),
                ('Description', models.TextField(blank=True, default='Mchanga kabisa', max_length=1000, null=True)),
                ('InformationImage', models.ImageField(blank=True, null=True, upload_to='media/LisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Week', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.weeks')),
            ],
            options={
                'verbose_name_plural': 'TaarifaZaUjauzito',
            },
        ),
        migrations.CreateModel(
            name='JeWajua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='WANGA', max_length=500)),
                ('Description', models.TextField(blank=True, default='Inasaidia kuimarisha misuli ya tumbo', max_length=1000, null=True)),
                ('ItemImage', models.ImageField(blank=True, null=True, upload_to='media/LisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
                ('Week', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.weeks')),
            ],
            options={
                'verbose_name_plural': 'JeWajua',
            },
        ),
    ]
