# Generated by Django 4.1.3 on 2023-08-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LisheApp', '0012_weeks_week9_week8_week7_week6_week5_week4_week3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week1',
            name='WeekName',
            field=models.CharField(default='Wiki 1', max_length=500),
        ),
        migrations.AlterField(
            model_name='week10',
            name='WeekName',
            field=models.CharField(default='Wiki 1', max_length=500),
        ),
        migrations.AlterField(
            model_name='week2',
            name='WeekName',
            field=models.CharField(default='Wiki 1', max_length=500),
        ),
        migrations.AlterField(
            model_name='week3',
            name='WeekName',
            field=models.CharField(default='Wiki 1', max_length=500),
        ),
        migrations.AlterField(
            model_name='week4',
            name='WeekName',
            field=models.CharField(default='Wiki 1', max_length=500),
        ),
        migrations.AlterField(
            model_name='week5',
            name='WeekName',
            field=models.CharField(default='Wiki 1', max_length=500),
        ),
        migrations.AlterField(
            model_name='week6',
            name='WeekName',
            field=models.CharField(default='Wiki 1', max_length=500),
        ),
        migrations.AlterField(
            model_name='week7',
            name='WeekName',
            field=models.CharField(default='Wiki 1', max_length=500),
        ),
        migrations.AlterField(
            model_name='week8',
            name='WeekName',
            field=models.CharField(default='Wiki 1', max_length=500),
        ),
        migrations.AlterField(
            model_name='week9',
            name='WeekName',
            field=models.CharField(default='Wiki 1', max_length=500),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='WeekName',
            field=models.CharField(default='Wiki 1', max_length=500),
        ),
    ]
