# Generated by Django 4.1.3 on 2023-08-22 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LisheApp', '0013_alter_week1_weekname_alter_week10_weekname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week10',
            name='WeekName',
            field=models.CharField(default='Wiki 10', max_length=500),
        ),
        migrations.AlterField(
            model_name='week2',
            name='WeekName',
            field=models.CharField(default='Wiki 2', max_length=500),
        ),
        migrations.AlterField(
            model_name='week3',
            name='WeekName',
            field=models.CharField(default='Wiki 3', max_length=500),
        ),
        migrations.AlterField(
            model_name='week4',
            name='WeekName',
            field=models.CharField(default='Wiki 4', max_length=500),
        ),
        migrations.AlterField(
            model_name='week5',
            name='WeekName',
            field=models.CharField(default='Wiki 5', max_length=500),
        ),
        migrations.AlterField(
            model_name='week6',
            name='WeekName',
            field=models.CharField(default='Wiki 6', max_length=500),
        ),
        migrations.AlterField(
            model_name='week7',
            name='WeekName',
            field=models.CharField(default='Wiki 7', max_length=500),
        ),
        migrations.AlterField(
            model_name='week8',
            name='WeekName',
            field=models.CharField(default='Wiki 8', max_length=500),
        ),
        migrations.AlterField(
            model_name='week9',
            name='WeekName',
            field=models.CharField(default='Wiki 9', max_length=500),
        ),
        migrations.CreateModel(
            name='Week45',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 45', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week45',
            },
        ),
        migrations.CreateModel(
            name='Week44',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 44', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week44',
            },
        ),
        migrations.CreateModel(
            name='Week43',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 43', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week43',
            },
        ),
        migrations.CreateModel(
            name='Week42',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 42', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week42',
            },
        ),
        migrations.CreateModel(
            name='Week41',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 41', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week41',
            },
        ),
        migrations.CreateModel(
            name='Week40',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 40', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week40',
            },
        ),
        migrations.CreateModel(
            name='Week39',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 39', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week39',
            },
        ),
        migrations.CreateModel(
            name='Week38',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 38', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week38',
            },
        ),
        migrations.CreateModel(
            name='Week37',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 37', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week37',
            },
        ),
        migrations.CreateModel(
            name='Week36',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 36', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week36',
            },
        ),
        migrations.CreateModel(
            name='Week35',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 35', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week35',
            },
        ),
        migrations.CreateModel(
            name='Week34',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 34', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week34',
            },
        ),
        migrations.CreateModel(
            name='Week33',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 33', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week33',
            },
        ),
        migrations.CreateModel(
            name='Week32',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 32', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week32',
            },
        ),
        migrations.CreateModel(
            name='Week31',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 31', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week31',
            },
        ),
        migrations.CreateModel(
            name='Week30',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 30', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week30',
            },
        ),
        migrations.CreateModel(
            name='Week29',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 29', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week29',
            },
        ),
        migrations.CreateModel(
            name='Week28',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 28', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week28',
            },
        ),
        migrations.CreateModel(
            name='Week27',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 27', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week27',
            },
        ),
        migrations.CreateModel(
            name='Week26',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 26', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week26',
            },
        ),
        migrations.CreateModel(
            name='Week25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 25', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week25',
            },
        ),
        migrations.CreateModel(
            name='Week24',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 24', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week24',
            },
        ),
        migrations.CreateModel(
            name='Week23',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 23', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week23',
            },
        ),
        migrations.CreateModel(
            name='Week22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 22', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week22',
            },
        ),
        migrations.CreateModel(
            name='Week21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 21', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week21',
            },
        ),
        migrations.CreateModel(
            name='Week20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 20', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week20',
            },
        ),
        migrations.CreateModel(
            name='Week19',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 19', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week19',
            },
        ),
        migrations.CreateModel(
            name='Week18',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 18', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week18',
            },
        ),
        migrations.CreateModel(
            name='Week17',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 17', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week17',
            },
        ),
        migrations.CreateModel(
            name='Week16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 16', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week16',
            },
        ),
        migrations.CreateModel(
            name='Week15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 15', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week15',
            },
        ),
        migrations.CreateModel(
            name='Week14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 14', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week14',
            },
        ),
        migrations.CreateModel(
            name='Week13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 13', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week13',
            },
        ),
        migrations.CreateModel(
            name='Week12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 12', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week12',
            },
        ),
        migrations.CreateModel(
            name='Week11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 11', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week11',
            },
        ),
        migrations.CreateModel(
            name='TaarifaZaWatoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='KULIA MARA KWA MARA', max_length=500)),
                ('Description', models.TextField(blank=True, default='Wiki ya kwanza kabisa', max_length=1000, null=True)),
                ('InformationImage', models.ImageField(blank=True, null=True, upload_to='media/LisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Week', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.weeks')),
            ],
            options={
                'verbose_name_plural': 'TaarifaZaWatoto',
            },
        ),
        migrations.CreateModel(
            name='TaarifaZaUzitoZaidi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='KUCHOKA MARA KWA MARA', max_length=500)),
                ('Description', models.TextField(blank=True, default='Wiki ya kwanza kabisa', max_length=1000, null=True)),
                ('InformationImage', models.ImageField(blank=True, null=True, upload_to='media/LisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Week', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.weeks')),
            ],
            options={
                'verbose_name_plural': 'TaarifaZaUzitoZaidi',
            },
        ),
        migrations.CreateModel(
            name='TaarifaZaKisukari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='MGONGO KUUMA', max_length=500)),
                ('Description', models.TextField(blank=True, default='Wiki ya kwanza kabisa', max_length=1000, null=True)),
                ('InformationImage', models.ImageField(blank=True, null=True, upload_to='media/LisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Week', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.weeks')),
            ],
            options={
                'verbose_name_plural': 'TaarifaZaKisukari',
            },
        ),
        migrations.CreateModel(
            name='TaarifaZaHiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='KUTOKWA NA VIPELE MWILINI', max_length=500)),
                ('Description', models.TextField(blank=True, default='Wiki ya kwanza kabisa', max_length=1000, null=True)),
                ('InformationImage', models.ImageField(blank=True, null=True, upload_to='media/LisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Week', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.weeks')),
            ],
            options={
                'verbose_name_plural': 'TaarifaZaHiv',
            },
        ),
        migrations.CreateModel(
            name='TaarifaZaFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='Description here', max_length=500)),
                ('Description', models.TextField(blank=True, default='Wiki ya kwanza kabisa', max_length=1000, null=True)),
                ('InformationImage', models.ImageField(blank=True, null=True, upload_to='media/LisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Week', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.weeks')),
            ],
            options={
                'verbose_name_plural': 'TaarifaZaFamilia',
            },
        ),
    ]
